<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lodging;
use App\Models\LodgingFacility;
use App\Models\Owner;

class LodgingSeeder extends Seeder
{
    /**
     * Seed 20 tempat Penginapan dan master fasilitas penginapan.
     */
    public function run(): void
    {
        // 1. Ambil sampel owner untuk relasi (jika ada)
        $firstOwner = Owner::first();
        $ownerId    = $firstOwner ? $firstOwner->id : null;

        // 2. Insert Master Fasilitas Penginapan (14 Fasilitas)
        $facilityNames = [
            'WiFi',
            'AC',
            'Restoran',
            'Lift',
            'Meeting Room',
            'Parkir',
            'Resepsionis 24 Jam',
            'Kolam Renang',
            'Gym',
            'Ballroom',
            'Gazebo',
            'Aula',
            'Dapur',
            'Taman',
        ];

        $facilityMap = [];
        foreach ($facilityNames as $name) {
            $fac = LodgingFacility::firstOrCreate(['facility_name' => $name]);
            $facilityMap[$name] = $fac->id;
        }

        // 3. Data 20 Tempat Penginapan
        $lodgingsData = [
            [
                'name'              => 'KHAS Gresik Hotel',
                'description'       => 'Hotel bintang tiga di pusat Kota Gresik yang cocok untuk perjalanan bisnis maupun wisata keluarga.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00 WIB',
                'check_out'         => '12.00 WIB',
                'address'           => 'Jl. Panglima Sudirman No.1, Sidokumpul, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Sidokumpul',
                'postal_code'       => '61111',
                'latitude'          => '-7.1610000',
                'longitude'         => '112.6520000',
                'google_maps'       => 'https://maps.google.com/?q=KHAS+Gresik+Hotel',
                'manager_name'      => 'KHAS Gresik Hotel',
                'email'             => null,
                'phone'             => '(031) 99006330',
                'website'           => null,
                'price_start'       => 550000,
                'price_end'         => 900000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Restoran', 'Lift', 'Meeting Room', 'Parkir', 'Resepsionis 24 Jam'],
            ],
            [
                'name'              => 'Aston Gresik Hotel & Conference Center',
                'description'       => 'Hotel modern berbintang empat di kawasan GKB Gresik yang menyajikan fasilitas lengkap, ballroom, dan layanan terbaik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Dr. Wahidin Sudirohusodo No. 116, Kembangan, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Kembangan',
                'postal_code'       => '61121',
                'latitude'          => '-7.1670000',
                'longitude'         => '112.6280000',
                'google_maps'       => 'https://maps.google.com/?q=Aston+Gresik+Hotel',
                'manager_name'      => 'Aston Hotels',
                'email'             => null,
                'phone'             => '(031) 39921777',
                'website'           => null,
                'price_start'       => 750000,
                'price_end'         => 1500000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'Kolam Renang', 'Gym', 'Ballroom', 'Restoran', 'Lift', 'Parkir'],
            ],
            [
                'name'              => 'Hotel Santika Gresik',
                'description'       => 'Hotel bisnis berbintang tiga yang berada dekat pusat perbelanjaan dan akses jalan tol Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Dr. Wahidin Sudirohusodo No. 788, Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Kembangan',
                'postal_code'       => '61121',
                'latitude'          => '-7.1665000',
                'longitude'         => '112.6290000',
                'google_maps'       => 'https://maps.google.com/?q=Hotel+Santika+Gresik',
                'manager_name'      => 'Santika Indonesia Hotels',
                'email'             => null,
                'phone'             => '(031) 39929777',
                'website'           => null,
                'price_start'       => 650000,
                'price_end'         => 1200000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'Gym', 'Restoran', 'Meeting Room', 'Lift', 'Parkir'],
            ],
            [
                'name'              => 'Horison GKB Gresik',
                'description'       => 'Hotel berbintang di perumahan GKB Gresik yang nyaman dengan kolam renang outdoor dan fasilitas meeting lengkap.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Kalimantan No. 12A, GKB, Kec. Manyar, Kabupaten Gresik',
                'district'          => 'Manyar',
                'village'           => 'Yosowilangun',
                'postal_code'       => '61151',
                'latitude'          => '-7.1520000',
                'longitude'         => '112.6100000',
                'google_maps'       => 'https://maps.google.com/?q=Hotel+Horison+GKB+Gresik',
                'manager_name'      => 'Horison Hotels',
                'email'             => null,
                'phone'             => '0811-3282-018',
                'website'           => null,
                'price_start'       => 600000,
                'price_end'         => 1100000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'Kolam Renang', 'Gym', 'Restoran', 'Parkir'],
            ],
            [
                'name'              => 'Front One Hotel Gresik',
                'description'       => 'Hotel stylish dan terjangkau di Gresik yang menawarkan tempat tinggal nyaman bagi pebisnis dan wisatawan.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Veteran No. 68, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Veteran',
                'postal_code'       => '61111',
                'latitude'          => '-7.1650000',
                'longitude'         => '112.6450000',
                'google_maps'       => 'https://maps.google.com/?q=Front+One+Hotel+Gresik',
                'manager_name'      => 'Front One',
                'email'             => null,
                'phone'             => '0816-818900',
                'website'           => null,
                'price_start'       => 350000,
                'price_end'         => 650000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'Restoran', 'Meeting Room', 'Parkir', 'AC'],
            ],
            [
                'name'              => 'Grab Hotel Gresik',
                'description'       => 'Penginapan budget praktis dengan lokasi strategis dan akses mudah menuju berbagai area industri Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Raya Dr. Soetomo No. 45, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Sidokumpul',
                'postal_code'       => '61111',
                'latitude'          => '-7.1630000',
                'longitude'         => '112.6500000',
                'google_maps'       => 'https://maps.google.com/?q=Grab+Hotel+Gresik',
                'manager_name'      => 'Grab Hotel',
                'email'             => null,
                'phone'             => '(031) 39923354',
                'website'           => null,
                'price_start'       => 250000,
                'price_end'         => 450000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir', 'Restoran'],
            ],
            [
                'name'              => 'Sapta Nawa Resort',
                'description'       => 'Resort berkonsep asri dengan area taman luas, kolam renang, dan aula serbaguna.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Suko Sunggono No. 1, Randuagung, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Randuagung',
                'postal_code'       => '61121',
                'latitude'          => '-7.1700000',
                'longitude'         => '112.6300000',
                'google_maps'       => 'https://maps.google.com/?q=Sapta+Nawa+Resort+Gresik',
                'manager_name'      => 'Sapta Nawa Resort',
                'email'             => null,
                'phone'             => '(031) 3971182',
                'website'           => null,
                'price_start'       => 350000,
                'price_end'         => 800000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['Kolam Renang', 'WiFi', 'Gazebo', 'Aula', 'Restoran', 'Parkir'],
            ],
            [
                'name'              => 'New Sinergi Hotel',
                'description'       => 'Hotel budget bersih dan nyaman dengan pelayanan ramah di pusat kota Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. DR. Wahidin Sudiro Husodo No. 89, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Randuagung',
                'postal_code'       => '61121',
                'latitude'          => '-7.1680000',
                'longitude'         => '112.6320000',
                'google_maps'       => 'https://maps.google.com/?q=New+Sinergi+Hotel+Gresik',
                'manager_name'      => 'New Sinergi Hotel',
                'email'             => null,
                'phone'             => '(021)29707601',
                'website'           => null,
                'price_start'       => 280000,
                'price_end'         => 450000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Restoran', 'Parkir'],
            ],
            [
                'name'              => 'Hotel Putra Jaya',
                'description'       => 'Akomodasi ekonomis berlokasi strategis untuk kunjungan singkat di Kabupaten Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Pahlawan No. 22, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Sidomoro',
                'postal_code'       => '61111',
                'latitude'          => '-7.1600000',
                'longitude'         => '112.6550000',
                'google_maps'       => 'https://maps.google.com/?q=Hotel+Putra+Jaya+Gresik',
                'manager_name'      => 'Hotel Putra Jaya',
                'email'             => null,
                'phone'             => '0813-3177-5555',
                'website'           => null,
                'price_start'       => 250000,
                'price_end'         => 400000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Restoran', 'Parkir'],
            ],
            [
                'name'              => 'Batik Hotel',
                'description'       => 'Hotel lokal yang tenang dengan fasilitas dasar lengkap dan tarif terjangkau.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. AKS Tubun No. 14, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Pekauman',
                'postal_code'       => '61111',
                'latitude'          => '-7.1580000',
                'longitude'         => '112.6540000',
                'google_maps'       => 'https://maps.google.com/?q=Batik+Hotel+Gresik',
                'manager_name'      => 'Batik Hotel',
                'email'             => null,
                'phone'             => '(031)3983610',
                'website'           => null,
                'price_start'       => 220000,
                'price_end'         => 380000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'Townhouse Oak Hotel Damar Kurung',
                'description'       => 'Penginapan bergaya townhouse bernuansa Damar Kurung yang unik dan bersih.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Damar Kurung No. 10, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Dahanrejo',
                'postal_code'       => '61121',
                'latitude'          => '-7.1720000',
                'longitude'         => '112.6350000',
                'google_maps'       => 'https://maps.google.com/?q=Townhouse+Oak+Hotel+Damar+Kurung',
                'manager_name'      => 'Townhouse Oak',
                'email'             => null,
                'phone'             => '0804-1040-040',
                'website'           => null,
                'price_start'       => 280000,
                'price_end'         => 450000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir', 'Resepsionis 24 Jam'],
            ],
            [
                'name'              => 'Kana Family Residence',
                'description'       => 'Residence keluarga bersih dan tenang untuk hunian harian maupun mingguan di Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Sunan Giri No. 45, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Kembangan',
                'postal_code'       => '61121',
                'latitude'          => '-7.1650000',
                'longitude'         => '112.6380000',
                'google_maps'       => 'https://maps.google.com/?q=Kana+Family+Residence+Gresik',
                'manager_name'      => 'Kana Family Residence',
                'email'             => null,
                'phone'             => null,
                'website'           => null,
                'price_start'       => 250000,
                'price_end'         => 350000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'Muzdalifa Syariah near Alun-Alun Gresik',
                'description'       => 'Penginapan berkonsep syariah yang bersih dan dekat dengan kawasan wisata religi Alun-Alun Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. K.H. Zubair No. 18, Near Alun-Alun, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Bedilan',
                'postal_code'       => '61111',
                'latitude'          => '-7.1590000',
                'longitude'         => '112.6570000',
                'google_maps'       => 'https://maps.google.com/?q=Muzdalifa+Syariah+Gresik',
                'manager_name'      => 'Muzdalifa Syariah',
                'email'             => null,
                'phone'             => '0813-2227-795',
                'website'           => null,
                'price_start'       => 180000,
                'price_end'         => 300000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'Vila dan Pondok Raima Syariah',
                'description'       => 'Penginapan villa syariah bernuansa pedesaan yang hijau dan sejuk di Gresik.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Raya Bungah No. 88, Kec. Bungah, Kabupaten Gresik',
                'district'          => 'Bungah',
                'village'           => 'Sungonlegowo',
                'postal_code'       => '61152',
                'latitude'          => '-7.0600000',
                'longitude'         => '112.5800000',
                'google_maps'       => 'https://maps.google.com/?q=Vila+dan+Pondok+Raima+Gresik',
                'manager_name'      => 'Raima Syariah',
                'email'             => null,
                'phone'             => '0812-6505-1815',
                'website'           => null,
                'price_start'       => 300000,
                'price_end'         => 600000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir', 'Taman'],
            ],
            [
                'name'              => 'SPOT ON 93144 Homestay Bandar Gresik 2',
                'description'       => 'Homestay ekonomis hemat biaya yang nyaman untuk backpacker dan perjalan hemat.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Raden Santri No. 12, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Bandar',
                'postal_code'       => '61111',
                'latitude'          => '-7.1570000',
                'longitude'         => '112.6560000',
                'google_maps'       => 'https://maps.google.com/?q=SPOT+ON+93144+Homestay+Bandar+Gresik+2',
                'manager_name'      => 'SPOT ON',
                'email'             => null,
                'phone'             => '0817-7880-16',
                'website'           => null,
                'price_start'       => 100000,
                'price_end'         => 180000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'SPOT ON 2479 Berkah Residence Syariah',
                'description'       => 'Penginapan syariah terjangkau dengan tempat tidur nyaman dan akses mudah.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Nyai Ageng Arem-Arem No. 5, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Kebungson',
                'postal_code'       => '61111',
                'latitude'          => '-7.1585000',
                'longitude'         => '112.6555000',
                'google_maps'       => 'https://maps.google.com/?q=Berkah+Residence+Syariah+Gresik',
                'manager_name'      => 'Berkah Residence',
                'email'             => null,
                'phone'             => null,
                'website'           => null,
                'price_start'       => 100000,
                'price_end'         => 200000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'OYO 3033 Pandawa Residence Syariah',
                'description'       => 'Hunian penginapan OYO bersyariat dengan fasilitas AC, tempat parkir, dan jaringan internet WiFi.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Veteran Madya No. 88, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Singosari',
                'postal_code'       => '61121',
                'latitude'          => '-7.1640000',
                'longitude'         => '112.6410000',
                'google_maps'       => 'https://maps.google.com/?q=Pandawa+Residence+Syariah+Gresik',
                'manager_name'      => 'Pandawa Residence',
                'email'             => null,
                'phone'             => null,
                'website'           => null,
                'price_start'       => 120000,
                'price_end'         => 220000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'Boarding House Gresik',
                'description'       => 'Fasilitas kos dan kamar sewa harian yang tenang dan terawat di Gresik Kota.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Jaksa Agung Suprapto No. 34, Kec. Gresik, Kabupaten Gresik',
                'district'          => 'Gresik',
                'village'           => 'Sidokumpul',
                'postal_code'       => '61111',
                'latitude'          => '-7.1615000',
                'longitude'         => '112.6510000',
                'google_maps'       => 'https://maps.google.com/?q=Boarding+House+Gresik',
                'manager_name'      => 'Boarding House Gresik',
                'email'             => null,
                'phone'             => '0813-9999-0300',
                'website'           => null,
                'price_start'       => 120000,
                'price_end'         => 250000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
            [
                'name'              => 'Sewa Apart Gresik',
                'description'       => 'Unit apartemen harian modern yang dilengkapi dapur, lift, dan ruang tengah luas.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Icon Apartment Gresik Tower B, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Kembangan',
                'postal_code'       => '61121',
                'latitude'          => '-7.1675000',
                'longitude'         => '112.6270000',
                'google_maps'       => 'https://maps.google.com/?q=Sewa+Apart+Gresik',
                'manager_name'      => 'Sewa Apart Gresik',
                'email'             => null,
                'phone'             => '0821-4169-9430',
                'website'           => null,
                'price_start'       => 300000,
                'price_end'         => 650000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Lift', 'Dapur', 'Parkir'],
            ],
            [
                'name'              => 'OYO 93785 Aero Kost Bu Lisa Syariah',
                'description'       => 'Penginapan kamar sewa syariah ekonomis di Gresik yang pas untuk singgah cepat.',
                'operational_hours' => '24 Jam',
                'check_in'          => '14.00',
                'check_out'         => '12.00',
                'address'           => 'Jl. Mayjend Sungkono No. 12, Kec. Kebomas, Kabupaten Gresik',
                'district'          => 'Kebomas',
                'village'           => 'Dahanrejo',
                'postal_code'       => '61121',
                'latitude'          => '-7.1710000',
                'longitude'         => '112.6340000',
                'google_maps'       => 'https://maps.google.com/?q=OYO+93785+Aero+Kost+Bu+Lisa',
                'manager_name'      => 'Aero Kost Bu Lisa',
                'email'             => null,
                'phone'             => null,
                'website'           => null,
                'price_start'       => 100000,
                'price_end'         => 180000,
                'thumbnail'         => null,
                'status'            => 'approved',
                'facilities'        => ['WiFi', 'AC', 'Parkir'],
            ],
        ];

        $hotelThumbnails = [
            'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
        ];

        foreach ($lodgingsData as $index => $item) {
            $facList = $item['facilities'];
            unset($item['facilities']);

            $item['owner_id']  = $ownerId;
            $item['thumbnail'] = $item['thumbnail'] ?? ($hotelThumbnails[$index % count($hotelThumbnails)] ?? null);

            $lodging = Lodging::create($item);

            // Sync fasilitas ke pivot table lodging_place_facility
            $facIds = [];
            foreach ($facList as $facName) {
                if (isset($facilityMap[$facName])) {
                    $facIds[] = $facilityMap[$facName];
                }
            }
            if (!empty($facIds)) {
                $lodging->facilities()->sync($facIds);
            }
        }
    }
}
